[package]
name = "volume_control_for_voicemeeter"
version = "0.1.2"
edition = "2021"
build = "build.rs"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
lerp = "0.5.0"
libm = "0.2.8"
smol = "2.0.0"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["sync"] }
tokio-graceful = "0.1.6"
tray-icon = "0.13.1"
voicemeeter = "0.3.0"
winit = "0.29.15"

[dependencies.windows]
version = "0.54.0"
features = [
	"implement",
	# "Foundation_Collections",
	"Win32_Foundation",
	"Win32_System_Com",
	"Win32_Media_Audio",
	"Win32_Media_Audio_Endpoints",
	"Win32_UI_Shell_PropertiesSystem",
	"Win32_System_Com_StructuredStorage",
	"Win32_Devices_FunctionDiscovery",
	"Win32_Devices_Properties",
	# "Win32_Storage",
	# "Win32_Globalization",
	# "Win32_System_Memory",
	"Win32_System_Threading",
	"Win32_System_Variant",
]
